#theme: jekyll-theme-cayman
remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: rakTech
  tagline: Apps by @thatvirtualboy
  date_format: "%b %-d, %Y"
  portfolio_image:  "assets/rakTech-logo.png" # the path from the base directory of the site to the image to display (no / at the start)

  social_links:
    twitter: thatvirtualboy
